services:
  bot:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - $PWD:/home/node
    restart: always
    networks:
      - bdd
    env_file:
      - .env
      - .env.tower
    depends_on:
      - mongodb
      - postgres
  mongodb:
    image: mongo:7.0
    restart: always
    volumes:
      - /opt/cds:/data/db
    networks:
      - bdd
    ports:
      - "27017:27017"
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: cds_user
      POSTGRES_PASSWORD: cds_pwd
      POSTGRES_DB: cds_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - /opt/cds:/var/lib/postgresql/data
    networks:
      - bdd
    ports:
      - "5432:5432"

volumes:
  cds_data:
  postgres_data:

networks:
  bdd:
    driver: bridge
