module.exports = {
    BaseModel: require("./BaseModel"),
    GuildConfig: require("./GuildConfig"),
    Game: require("./Game"),
    Achievement: require("./Achievement"),
    User: require("./User"),
    Group: require("./Group"),
    GroupUser: require("./GroupUser"),
    Observation: require("./Observation"),
    Stats: require("./Stats"),
    MessageClue: require("./MessageClue"),
    ClueField: require("./ClueField"),
    Tower: require("./Tower"),
    TowerBoss: require("./TowerBoss"),
    TowerStats: require("./TowerStats"),
    Job: require("./Job"),
    UserMetaAchievementTiers: require("./UserMetaAchievementTiers"),
    MetaAchievements: require("./MetaAchievements"),
    MetaAchievementTiers: require("./MetaAchievementTiers"),
};
